---
driver:
  name: terraform
  parallelism: 4
     
provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: terraform

suites:
  - name: vpc_suite
    driver:
      root_module_directory: test/fixtures/tf_module
      variable_files:
        - test/fixtures/tf_module/test.tfvars
    verifier:
      systems:
        - name: vpc
          backend: local
