---
driver:
  name: terraform
  parallelism: 4
     
provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: terraform

suites:
  - name: vpc_suite
    driver:
      root_module_directory: test/fixtures/tf_module
      // variable_files:
      //  - test/fixtures/test-variable.tf
      variables:
        project_id: searce-academy
    verifier:
      systems:
        - name: vpc
          backend: local
